package com.minlauncher.min

enum class Constants(val VALUE: String) {
    SHARED_PREFERENCES_APP_LIST("SHARED_PREFERENCES_APP_LIST"),
    SHARED_PREFERENCES_APP_LIST_KEY("SHARED_PREFERENCES_APP_LIST_KEY"),

    DARK_MODE_SHARED_PREFERENCES_NAME("DARK_MODE_SHARED_PREFERENCES_NAME"),
    DARK_MODE_SHARED_PREFERENCES_KEY("DARK_MODE_SHARED_PREFERENCES_KEY"),

    DARK_MODE_ON("DARK_MODE_ON"),
    DARK_MODE_OFF("DARK_MODE_OFF"),

    SHARED_PREFERENCES_SETTINGS("SHARED_PREFERENCES_SETTINGS"),
    SHARED_PREFERENCES_SETTINGS_KEY_PREFIX("SHARED_PREFERENCES_SETTINGS_KEY_PREFIX")
}