package com.minlauncher.min

enum class Constants(val value: String) {
    SHARED_PREFERENCES_NAME("HOME"),
    SHARED_PREFERENCES_HOME_APPS_KEY("SHARED_PREFERENCES_HOME_APPS_KEY"),
    REFRESH_HOME_INTENT("REFRESH_HOME_INTENT"),
    DARK_MODE_SHARED_PREFERENCES_NAME("DARK_MODE_SHARED_PREFERENCES_NAME"),
    DARK_MODE_SHARED_PREFERENCES_KEY("DARK_MODE_SHARED_PREFERENCES_KEY"),
    DARK_MODE_ON("DARK_MODE_ON"),
    DARK_MODE_OFF("DARK_MODE_OFF")
}