package com.minlauncher.min

enum class Constants(val VALUE: String) {
    SHARED_PREFERENCES_SETTINGS("SHARED_PREFERENCES_SETTINGS"),
    SHARED_PREFERENCES_SETTINGS_KEY_PREFIX("SHARED_PREFERENCES_SETTINGS_KEY_PREFIX")
}