package com.minlauncher.min

enum class Settings(val NAME: String) {
    ICONS_ON_HOME_SCREEN("ICONS_ON_HOME_SCREEN"),
    HIDE_ICONS("HIDE_ICONS"),
    HIDE_NOTIFICATIONS("HIDE_NOTIFICATIONS"),
    HIDE_HOME("HIDE_HOME"),
    HIDE_LAST_USED_APPS("HIDE_LAST_USED_APPS"),
    DARK_MODE("DARK_MODE")
}